[features]
seeds = false
skip-lint = false
[programs.localnet]
digital_identity = "7E6f2pscJXdX8Jb1jbxE4ir5LPEqTH3FiLg4HQXTU11P"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/nags/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
